[supervisord]
user=root
nodaemon=true


[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=2

[program:redis]
command=redis-server --save "" --appendonly no
autostart=true
autorestart=true
priority=2

[program:auth]
command=/usr/local/bin/auth-server
autostart=true
autorestart=true
priority=3

[program:project-manager]
command=/usr/local/bin/project-manager
autostart=true
autorestart=true
priority=3

[program:db-proxy]
command=/usr/local/bin/db-proxy
autostart=true
autorestart=true
priority=3

[program:storage]
command=/usr/local/bin/storage
autostart=true
autorestart=true
priority=3

[program:sql-editor]
command=/usr/local/bin/sql-editor
autostart=true
autorestart=true
priority=3

[program:edge-functions]
command=/usr/local/bin/edge-functions
autostart=true
autorestart=true
priority=3

[program:ai-assistant]
command=python3 /app/ai-assistant/main.py
autostart=true
autorestart=true
priority=3
